### ISSUE TITLE
Screen freezes at the end of simulation

### ISSUE THREAD

**Issue by enter802** [Stanford-ILIAD/CARLO#5] opened 2022-02-04 14:35 UTC
At the end of the simulation, i.e., when the animation stops and then I try to close the CARLO screen, the screen freezes. Eventually, it closes but raises a fatal error that requires restarting the kernel.

I am running Python 3.9 in Spyder (Anaconda). Any help with this would be highly appreciated.

By the way, a great piece of work and contribution to the community!

**Comment by ebiyik** [comment] 2022-02-04 20:55
Hello,
Do you get the error while running some of the examples we have in the repository? If not, can you share a minimal running example so that we can reproduce the error?
Thank you!

**Comment by enter802** [comment] 2022-02-04 21:04
Hi, thanks for the prompt response!

Yes, I get the error while running the example "example_intersection".

Just to make it clear - the code executes perfectly fine (see the first screenshot), however, when I close the "CARLO window, it does not close first of all (even with repetitive attempts to close), however, it eventually closes by itself raising the error (see the second screenshot - I could not capture the full error with ss)

![image](https://user-images.githubusercontent.com/9440833/152602341-6866336c-9240-4f71-abcd-13e291f7541b.png)

![image](https://user-images.githubusercontent.com/9440833/152602891-4f352bb5-e27a-492e-ab98-193de4e52976.png)

**Comment by ebiyik** [comment] 2022-02-05 00:59
I was not able to reproduce it, but I think the issue is because your terminal does not terminate the window automatically when the code finishes running. I just pushed a new commit which programmatically closes the UI objects. Can you try the new example runner?

**Comment by enter802** [comment] 2022-02-05 04:04
Yes, it did work! Now it automatically closes and thus not an issue. Thanks a lot!

I was wondering though if there is a way to get the map with the objects as a figure (e.g., matplotlib figure) so that I can do static plots similar to the one below (thanks once again in advance):

![image](https://user-images.githubusercontent.com/9440833/152627997-7da196e7-4047-4357-bc59-bf12dedb6a7d.png)

**Comment by ebiyik** [comment] 2022-02-15 21:32
Nice! Closing this issue now.

RE getting the environment state as an image: It is possible, but tricky. And that's why it is not in the public release of CARLO. Please refer to [this discussion](https://stackoverflow.com/questions/9886274/how-can-i-convert-canvas-content-to-an-image) and note world.visualizer.win is a Tkinter Canvas object. So using the techniques described in that discussion, you should be able to get an image of that canvas object, which visualizes the world. 

P.S.: To keep things organized (and easily searchable), you can create a new issue for every new bug/request. Cheers!

**Closed as completed by ebiyik** 2022-02-15 21:32 UTC
